name: health_car_demo_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_blue_plus: ^1.32.4
  flutter_foreground_task: ^6.2.0
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  google_fonts: ^6.2.1
  google_mlkit_image_labeling: ^0.11.1
  intl: ^0.18.0
  permission_handler: ^11.3.1

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
