name: backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  data_sources:
    path: ../data_sources
  dotenv: ^4.2.0
  either_dart: ^1.0.0
  exceptions: 
    path: ../exceptions
  failures: 
    path: ../failures
  mongo_dart: ^0.10.2
  models: 
    path: ../models
  repository: 
    path: ../repository

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
